use_frameworks!

platform :ios, '8.0'

target 'CSNetwork_Example' do
  pod 'CSNetwork', :path => '../'

  target 'CSNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
